/**
 * completion.ts — Shell completion script generator for wombo-combo.
 *
 * Generates native completion scripts for bash, zsh, and fish.
 *
 * Install:
 *   eval "$(woco completion bash)"                          # add to ~/.bashrc
 *   eval "$(woco completion zsh)"                           # add to ~/.zshrc
 *   woco completion fish | source                           # fish
 *   woco completion fish > ~/.config/fish/completions/woco.fish  # persist
 */

import { basename } from "node:path";

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function cmdCompletion({ shell }: { shell?: string }): void {
  const resolved = shell ?? detectShell();

  switch (resolved) {
    case "bash":
      process.stdout.write(bashScript());
      break;
    case "zsh":
      process.stdout.write(zshScript());
      break;
    case "fish":
      process.stdout.write(fishScript());
      break;
    default:
      console.error(`Unsupported shell: "${resolved}"`);
      console.error("Supported shells: bash, zsh, fish");
      console.error("");
      console.error("Install completions:");
      console.error('  eval "$(woco completion bash)"    # Bash: add to ~/.bashrc');
      console.error('  eval "$(woco completion zsh)"     # Zsh:  add to ~/.zshrc');
      console.error("  woco completion fish | source     # Fish");
      process.exit(1);
  }
}

// ---------------------------------------------------------------------------
// Shell detection
// ---------------------------------------------------------------------------

function detectShell(): string {
  const shellPath = process.env.SHELL || "";
  const name = basename(shellPath);
  if (name === "bash" || name === "zsh" || name === "fish") return name;
  return "bash"; // safe default
}

// ---------------------------------------------------------------------------
// Bash completion
// ---------------------------------------------------------------------------

function bashScript(): string {
  return `# woco (wombo-combo) bash completion
# Generated by: woco completion bash
# Install: eval "$(woco completion bash)"  — add to ~/.bashrc

_woco_completions() {
    local cur prev cmd subcmd i j
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"
    cmd=""
    subcmd=""

    # Find the main command (first non-flag arg after woco)
    for ((i=1; i < COMP_CWORD; i++)); do
        if [[ "\${COMP_WORDS[i]}" != -* ]]; then
            cmd="\${COMP_WORDS[i]}"
            break
        fi
    done

    # Resolve top-level aliases
    case "$cmd" in
        i) cmd="init" ;; l) cmd="launch" ;; r) cmd="resume" ;;
        s) cmd="status" ;; v) cmd="verify" ;; m) cmd="merge" ;;
        re) cmd="retry" ;; a) cmd="abort" ;; c) cmd="cleanup" ;;
        h) cmd="history" ;; lo) cmd="logs" ;; t|features) cmd="tasks" ;;
        u) cmd="upgrade" ;; d) cmd="describe" ;; comp) cmd="completion" ;;
    esac

    # Flag value completions (context-independent)
    case "$prev" in
        --priority)
            COMPREPLY=($(compgen -W "critical high medium low wishlist" -- "$cur")); return ;;
        --difficulty)
            COMPREPLY=($(compgen -W "trivial easy medium hard very_hard" -- "$cur")); return ;;
        --status)
            COMPREPLY=($(compgen -W "backlog planned in_progress blocked in_review done cancelled" -- "$cur")); return ;;
        --output|-o)
            COMPREPLY=($(compgen -W "text json toon" -- "$cur")); return ;;
        --model|-m|--top-priority|--quickest-wins|--max-concurrent|--max-retries|--tail|--base-branch|--tag|--release|--tasks|--features|--fields|--desc|--description|--effort|--depends-on|--title)
            return ;;  # free-form / numeric — no completions, let readline handle it
    esac

    # No command yet → complete commands
    if [[ -z "$cmd" ]]; then
        COMPREPLY=($(compgen -W "init i launch l resume r status s verify v merge m retry re abort a cleanup c history h logs lo tasks t upgrade u describe d completion comp version help" -- "$cur"))
        return
    fi

    # tasks / t → subcommands
    if [[ "$cmd" == "tasks" ]]; then
        # Find the subcommand
        for ((j=i+1; j < COMP_CWORD; j++)); do
            if [[ "\${COMP_WORDS[j]}" != -* ]]; then
                subcmd="\${COMP_WORDS[j]}"
                break
            fi
        done

        # Resolve subcommand aliases
        case "$subcmd" in
            ls) subcmd="list" ;; a) subcmd="add" ;; ss) subcmd="set-status" ;;
            sp) subcmd="set-priority" ;; sd) subcmd="set-difficulty" ;;
            ch|validate) subcmd="check" ;; ar) subcmd="archive" ;;
            sh) subcmd="show" ;; g) subcmd="graph" ;;
        esac

        # No subcommand yet → complete subcommands
        if [[ -z "$subcmd" ]]; then
            COMPREPLY=($(compgen -W "list ls add a set-status ss set-priority sp set-difficulty sd check ch validate archive ar show sh graph g help" -- "$cur"))
            return
        fi

        # Flags per tasks subcommand
        case "$subcmd" in
            list)
                COMPREPLY=($(compgen -W "--status --priority --difficulty --ready --include-archive --output -o --fields" -- "$cur")) ;;
            add)
                COMPREPLY=($(compgen -W "--desc --description --priority --difficulty --effort --depends-on --dry-run --output -o" -- "$cur")) ;;
            set-status|set-priority|set-difficulty)
                COMPREPLY=($(compgen -W "--output -o --dry-run" -- "$cur")) ;;
            archive)
                COMPREPLY=($(compgen -W "--dry-run --output -o" -- "$cur")) ;;
            show)
                COMPREPLY=($(compgen -W "--output -o --fields" -- "$cur")) ;;
            graph)
                COMPREPLY=($(compgen -W "--ascii --mermaid --subtasks --status --output -o" -- "$cur")) ;;
        esac
        return
    fi

    # completion → shell names
    if [[ "$cmd" == "completion" ]]; then
        COMPREPLY=($(compgen -W "bash zsh fish" -- "$cur"))
        return
    fi

    # describe → command names (for introspection)
    if [[ "$cmd" == "describe" ]]; then
        COMPREPLY=($(compgen -W "init launch resume status verify merge retry abort cleanup history logs tasks upgrade describe completion version help" -- "$cur"))
        return
    fi

    # Flags per top-level command
    case "$cmd" in
        init)
            COMPREPLY=($(compgen -W "--force" -- "$cur")) ;;
        launch)
            COMPREPLY=($(compgen -W "--top-priority --quickest-wins --priority --difficulty --tasks --features --all-ready --max-concurrent --model -m --interactive --no-tui --auto-push --base-branch --max-retries --browser --dry-run --output -o --force" -- "$cur")) ;;
        resume)
            COMPREPLY=($(compgen -W "--max-concurrent --model -m --interactive --no-tui --auto-push --base-branch --max-retries" -- "$cur")) ;;
        status)
            COMPREPLY=($(compgen -W "--output -o" -- "$cur")) ;;
        verify)
            COMPREPLY=($(compgen -W "--model -m --max-retries --browser" -- "$cur")) ;;
        merge)
            COMPREPLY=($(compgen -W "--auto-push --dry-run --model -m" -- "$cur")) ;;
        retry)
            COMPREPLY=($(compgen -W "--model -m --interactive --dry-run" -- "$cur")) ;;
        abort)
            COMPREPLY=($(compgen -W "--requeue --output -o" -- "$cur")) ;;
        cleanup)
            COMPREPLY=($(compgen -W "--dry-run" -- "$cur")) ;;
        history)
            COMPREPLY=($(compgen -W "--output -o" -- "$cur")) ;;
        logs)
            COMPREPLY=($(compgen -W "--tail --follow -f --output -o" -- "$cur")) ;;
        upgrade)
            COMPREPLY=($(compgen -W "--check --tag --release --force" -- "$cur")) ;;
    esac
}

complete -o default -F _woco_completions woco
`;
}

// ---------------------------------------------------------------------------
// Zsh completion
// ---------------------------------------------------------------------------

function zshScript(): string {
  return `#compdef woco
# woco (wombo-combo) zsh completion
# Generated by: woco completion zsh
# Install: eval "$(woco completion zsh)"  — add to ~/.zshrc

_woco() {
    local cmd subcmd

    # Position 2 → completing the main command
    if (( CURRENT == 2 )); then
        local -a cmds
        cmds=(
            'init:Generate .wombo-combo/config.json (i)'
            'i:→ init'
            'launch:Launch a wave of agents (l)'
            'l:→ launch'
            'resume:Resume a stopped wave (r)'
            'r:→ resume'
            'status:Show wave status (s)'
            's:→ status'
            'verify:Run build verification (v)'
            'v:→ verify'
            'merge:Merge verified branches (m)'
            'm:→ merge'
            'retry:Retry a failed agent (re)'
            're:→ retry'
            'abort:Kill a running agent (a)'
            'a:→ abort'
            'cleanup:Remove worktrees and sessions (c)'
            'c:→ cleanup'
            'history:List/view past waves (h)'
            'h:→ history'
            'logs:Pretty-print agent logs (lo)'
            'lo:→ logs'
            'tasks:Manage tasks file (t)'
            't:→ tasks'
            'upgrade:Check for updates (u)'
            'u:→ upgrade'
            'describe:Emit JSON schema (d)'
            'd:→ describe'
            'completion:Generate shell completions (comp)'
            'comp:→ completion'
            'version:Print version'
            'help:Show help'
        )
        _describe 'command' cmds
        return
    fi

    cmd="\${words[2]}"

    # Resolve top-level aliases
    case "$cmd" in
        i) cmd=init ;; l) cmd=launch ;; r) cmd=resume ;;
        s) cmd=status ;; v) cmd=verify ;; m) cmd=merge ;;
        re) cmd=retry ;; a) cmd=abort ;; c) cmd=cleanup ;;
        h) cmd=history ;; lo) cmd=logs ;; t|features) cmd=tasks ;;
        u) cmd=upgrade ;; d) cmd=describe ;; comp) cmd=completion ;;
    esac

    # Flag value completions
    case "\${words[CURRENT-1]}" in
        --priority)    compadd critical high medium low wishlist; return ;;
        --difficulty)  compadd trivial easy medium hard very_hard; return ;;
        --status)      compadd backlog planned in_progress blocked in_review done cancelled; return ;;
        --output|-o)   compadd text json toon; return ;;
    esac

    # tasks → subcommands
    if [[ "$cmd" == "tasks" ]]; then
        if (( CURRENT == 3 )); then
            local -a subcmds
            subcmds=(
                'list:List tasks (ls)'
                'ls:→ list'
                'add:Add a new task (a)'
                'a:→ add'
                'set-status:Change task status (ss)'
                'ss:→ set-status'
                'set-priority:Change task priority (sp)'
                'sp:→ set-priority'
                'set-difficulty:Change task difficulty (sd)'
                'sd:→ set-difficulty'
                'check:Validate tasks file (ch)'
                'ch:→ check'
                'validate:→ check'
                'archive:Move done/cancelled to archive (ar)'
                'ar:→ archive'
                'show:Show task details (sh)'
                'sh:→ show'
                'graph:Visualize dependency graph (g)'
                'g:→ graph'
                'help:Show help'
            )
            _describe 'subcommand' subcmds
            return
        fi

        subcmd="\${words[3]}"
        case "$subcmd" in
            ls) subcmd=list ;; a) subcmd=add ;; ss) subcmd=set-status ;;
            sp) subcmd=set-priority ;; sd) subcmd=set-difficulty ;;
            ch|validate) subcmd=check ;; ar) subcmd=archive ;;
            sh) subcmd=show ;; g) subcmd=graph ;;
        esac

        case "$subcmd" in
            list)
                compadd -- --status --priority --difficulty --ready --include-archive --output -o --fields ;;
            add)
                compadd -- --desc --description --priority --difficulty --effort --depends-on --dry-run --output -o ;;
            set-status|set-priority|set-difficulty)
                compadd -- --output -o --dry-run ;;
            archive)
                compadd -- --dry-run --output -o ;;
            show)
                compadd -- --output -o --fields ;;
            graph)
                compadd -- --ascii --mermaid --subtasks --status --output -o ;;
        esac
        return
    fi

    # completion → shell names
    if [[ "$cmd" == "completion" ]]; then
        if (( CURRENT == 3 )); then
            compadd bash zsh fish
        fi
        return
    fi

    # describe → command names
    if [[ "$cmd" == "describe" ]]; then
        compadd -- init launch resume status verify merge retry abort cleanup history logs tasks upgrade describe completion version help
        return
    fi

    # Flags per command
    case "$cmd" in
        init)     compadd -- --force ;;
        launch)   compadd -- --top-priority --quickest-wins --priority --difficulty --tasks --features --all-ready --max-concurrent --model -m --interactive --no-tui --auto-push --base-branch --max-retries --browser --dry-run --output -o --force ;;
        resume)   compadd -- --max-concurrent --model -m --interactive --no-tui --auto-push --base-branch --max-retries ;;
        status)   compadd -- --output -o ;;
        verify)   compadd -- --model -m --max-retries --browser ;;
        merge)    compadd -- --auto-push --dry-run --model -m ;;
        retry)    compadd -- --model -m --interactive --dry-run ;;
        abort)    compadd -- --requeue --output -o ;;
        cleanup)  compadd -- --dry-run ;;
        history)  compadd -- --output -o ;;
        logs)     compadd -- --tail --follow -f --output -o ;;
        upgrade)  compadd -- --check --tag --release --force ;;
    esac
}

compdef _woco woco
`;
}

// ---------------------------------------------------------------------------
// Fish completion
// ---------------------------------------------------------------------------

function fishScript(): string {
  return `# woco (wombo-combo) fish completion
# Generated by: woco completion fish
# Install: woco completion fish | source
# Persist: woco completion fish > ~/.config/fish/completions/woco.fish

# Helper: true when the tasks/t/features subcommand has a specific sub-subcommand
function __woco_tasks_subcmd
    set -l tokens (commandline -opc)
    if test (count $tokens) -ge 3
        switch $tokens[2]
            case tasks t features
                for sub in $argv
                    if test "$tokens[3]" = "$sub"
                        return 0
                    end
                end
        end
    end
    return 1
end

# Helper: true when we need a tasks subcommand (exactly: woco tasks <cursor>)
function __woco_needs_tasks_subcmd
    set -l tokens (commandline -opc)
    if test (count $tokens) -eq 2
        switch $tokens[2]
            case tasks t features
                return 0
        end
    end
    return 1
end

# Disable file completions by default
for cmd in woco
    complete -c $cmd -f

    # --- Top-level commands ---
    complete -c $cmd -n '__fish_use_subcommand' -a 'init'       -d 'Generate config'
    complete -c $cmd -n '__fish_use_subcommand' -a 'i'          -d '→ init'
    complete -c $cmd -n '__fish_use_subcommand' -a 'launch'     -d 'Launch agents'
    complete -c $cmd -n '__fish_use_subcommand' -a 'l'          -d '→ launch'
    complete -c $cmd -n '__fish_use_subcommand' -a 'resume'     -d 'Resume wave'
    complete -c $cmd -n '__fish_use_subcommand' -a 'r'          -d '→ resume'
    complete -c $cmd -n '__fish_use_subcommand' -a 'status'     -d 'Show wave status'
    complete -c $cmd -n '__fish_use_subcommand' -a 's'          -d '→ status'
    complete -c $cmd -n '__fish_use_subcommand' -a 'verify'     -d 'Build verification'
    complete -c $cmd -n '__fish_use_subcommand' -a 'v'          -d '→ verify'
    complete -c $cmd -n '__fish_use_subcommand' -a 'merge'      -d 'Merge branches'
    complete -c $cmd -n '__fish_use_subcommand' -a 'm'          -d '→ merge'
    complete -c $cmd -n '__fish_use_subcommand' -a 'retry'      -d 'Retry failed agent'
    complete -c $cmd -n '__fish_use_subcommand' -a 're'         -d '→ retry'
    complete -c $cmd -n '__fish_use_subcommand' -a 'abort'      -d 'Kill running agent'
    complete -c $cmd -n '__fish_use_subcommand' -a 'a'          -d '→ abort'
    complete -c $cmd -n '__fish_use_subcommand' -a 'cleanup'    -d 'Remove worktrees'
    complete -c $cmd -n '__fish_use_subcommand' -a 'c'          -d '→ cleanup'
    complete -c $cmd -n '__fish_use_subcommand' -a 'history'    -d 'View past waves'
    complete -c $cmd -n '__fish_use_subcommand' -a 'h'          -d '→ history'
    complete -c $cmd -n '__fish_use_subcommand' -a 'logs'       -d 'Agent logs'
    complete -c $cmd -n '__fish_use_subcommand' -a 'lo'         -d '→ logs'
    complete -c $cmd -n '__fish_use_subcommand' -a 'tasks'      -d 'Manage tasks'
    complete -c $cmd -n '__fish_use_subcommand' -a 't'          -d '→ tasks'
    complete -c $cmd -n '__fish_use_subcommand' -a 'upgrade'    -d 'Check for updates'
    complete -c $cmd -n '__fish_use_subcommand' -a 'u'          -d '→ upgrade'
    complete -c $cmd -n '__fish_use_subcommand' -a 'describe'   -d 'Emit JSON schema'
    complete -c $cmd -n '__fish_use_subcommand' -a 'd'          -d '→ describe'
    complete -c $cmd -n '__fish_use_subcommand' -a 'completion' -d 'Shell completions'
    complete -c $cmd -n '__fish_use_subcommand' -a 'comp'       -d '→ completion'
    complete -c $cmd -n '__fish_use_subcommand' -a 'version'    -d 'Print version'
    complete -c $cmd -n '__fish_use_subcommand' -a 'help'       -d 'Show help'

    # --- tasks subcommands ---
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'list'           -d 'List tasks'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'ls'             -d '→ list'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'add'            -d 'Add task'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'a'              -d '→ add'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'set-status'     -d 'Change status'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'ss'             -d '→ set-status'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'set-priority'   -d 'Change priority'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'sp'             -d '→ set-priority'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'set-difficulty' -d 'Change difficulty'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'sd'             -d '→ set-difficulty'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'check'          -d 'Validate tasks'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'ch'             -d '→ check'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'validate'       -d '→ check'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'archive'        -d 'Archive done tasks'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'ar'             -d '→ archive'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'show'           -d 'Show task details'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'sh'             -d '→ show'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'graph'          -d 'Dependency graph'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'g'              -d '→ graph'
    complete -c $cmd -n '__woco_needs_tasks_subcmd' -a 'help'           -d 'Show help'

    # --- completion subcommand ---
    complete -c $cmd -n '__fish_seen_subcommand_from completion comp' -a 'bash zsh fish'

    # --- describe subcommand ---
    complete -c $cmd -n '__fish_seen_subcommand_from describe d' -a 'init launch resume status verify merge retry abort cleanup history logs tasks upgrade describe completion version help'

    # --- Flags: init ---
    complete -c $cmd -n '__fish_seen_subcommand_from init i' -l force -d 'Force overwrite'

    # --- Flags: launch ---
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -l top-priority    -d 'Select top N by priority' -x
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -l quickest-wins   -d 'Select N lowest effort' -x
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -l priority        -d 'Filter by priority' -xa 'critical high medium low wishlist'
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -l difficulty      -d 'Filter by difficulty' -xa 'trivial easy medium hard very_hard'
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -l tasks           -d 'Select tasks by ID' -x
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -l features        -d '→ --tasks' -x
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -l all-ready       -d 'All ready tasks'
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -l max-concurrent  -d 'Max parallel agents' -x
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -l model           -d 'Model to use' -x
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -s m               -d 'Model to use' -x
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -l interactive     -d 'Multiplexer TUI mode'
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -l no-tui          -d 'Headless mode'
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -l auto-push       -d 'Push after merges'
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -l base-branch     -d 'Base branch' -x
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -l max-retries     -d 'Max retries' -x
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -l browser         -d 'Browser verification'
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -l dry-run         -d 'Show without launching'
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -l output          -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -s o               -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__fish_seen_subcommand_from launch l' -l force           -d 'Force'

    # --- Flags: resume ---
    complete -c $cmd -n '__fish_seen_subcommand_from resume r' -l max-concurrent -d 'Max parallel agents' -x
    complete -c $cmd -n '__fish_seen_subcommand_from resume r' -l model          -d 'Model to use' -x
    complete -c $cmd -n '__fish_seen_subcommand_from resume r' -s m              -d 'Model to use' -x
    complete -c $cmd -n '__fish_seen_subcommand_from resume r' -l interactive    -d 'Multiplexer TUI mode'
    complete -c $cmd -n '__fish_seen_subcommand_from resume r' -l no-tui         -d 'Headless mode'
    complete -c $cmd -n '__fish_seen_subcommand_from resume r' -l auto-push      -d 'Push after merges'
    complete -c $cmd -n '__fish_seen_subcommand_from resume r' -l base-branch    -d 'Base branch' -x
    complete -c $cmd -n '__fish_seen_subcommand_from resume r' -l max-retries    -d 'Max retries' -x

    # --- Flags: status ---
    complete -c $cmd -n '__fish_seen_subcommand_from status s' -l output -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__fish_seen_subcommand_from status s' -s o      -d 'Output format' -xa 'text json toon'

    # --- Flags: verify ---
    complete -c $cmd -n '__fish_seen_subcommand_from verify v' -l model       -d 'Model to use' -x
    complete -c $cmd -n '__fish_seen_subcommand_from verify v' -s m           -d 'Model to use' -x
    complete -c $cmd -n '__fish_seen_subcommand_from verify v' -l max-retries -d 'Max retries' -x
    complete -c $cmd -n '__fish_seen_subcommand_from verify v' -l browser     -d 'Browser verification'

    # --- Flags: merge ---
    complete -c $cmd -n '__fish_seen_subcommand_from merge m' -l auto-push -d 'Push after merge'
    complete -c $cmd -n '__fish_seen_subcommand_from merge m' -l dry-run   -d 'Show without merging'
    complete -c $cmd -n '__fish_seen_subcommand_from merge m' -l model     -d 'Model to use' -x
    complete -c $cmd -n '__fish_seen_subcommand_from merge m' -s m         -d 'Model to use' -x

    # --- Flags: retry ---
    complete -c $cmd -n '__fish_seen_subcommand_from retry re' -l model       -d 'Model to use' -x
    complete -c $cmd -n '__fish_seen_subcommand_from retry re' -s m           -d 'Model to use' -x
    complete -c $cmd -n '__fish_seen_subcommand_from retry re' -l interactive -d 'Interactive mode'
    complete -c $cmd -n '__fish_seen_subcommand_from retry re' -l dry-run     -d 'Dry run'

    # --- Flags: abort ---
    complete -c $cmd -n '__fish_seen_subcommand_from abort a' -l requeue -d 'Return task to queue'
    complete -c $cmd -n '__fish_seen_subcommand_from abort a' -l output  -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__fish_seen_subcommand_from abort a' -s o       -d 'Output format' -xa 'text json toon'

    # --- Flags: cleanup ---
    complete -c $cmd -n '__fish_seen_subcommand_from cleanup c' -l dry-run -d 'Show without cleaning'

    # --- Flags: history ---
    complete -c $cmd -n '__fish_seen_subcommand_from history h' -l output -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__fish_seen_subcommand_from history h' -s o      -d 'Output format' -xa 'text json toon'

    # --- Flags: logs ---
    complete -c $cmd -n '__fish_seen_subcommand_from logs lo' -l tail   -d 'Show last N lines' -x
    complete -c $cmd -n '__fish_seen_subcommand_from logs lo' -l follow -d 'Stream output'
    complete -c $cmd -n '__fish_seen_subcommand_from logs lo' -s f      -d 'Stream output'
    complete -c $cmd -n '__fish_seen_subcommand_from logs lo' -l output -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__fish_seen_subcommand_from logs lo' -s o      -d 'Output format' -xa 'text json toon'

    # --- Flags: upgrade ---
    complete -c $cmd -n '__fish_seen_subcommand_from upgrade u' -l check   -d 'Check only'
    complete -c $cmd -n '__fish_seen_subcommand_from upgrade u' -l tag     -d 'Specific version' -x
    complete -c $cmd -n '__fish_seen_subcommand_from upgrade u' -l release -d '→ --tag' -x
    complete -c $cmd -n '__fish_seen_subcommand_from upgrade u' -l force   -d 'Skip prompts'

    # --- Flags: tasks subcommand-specific ---
    complete -c $cmd -n '__woco_tasks_subcmd list ls'   -l status          -d 'Filter by status' -xa 'backlog planned in_progress blocked in_review done cancelled'
    complete -c $cmd -n '__woco_tasks_subcmd list ls'   -l priority        -d 'Filter by priority' -xa 'critical high medium low wishlist'
    complete -c $cmd -n '__woco_tasks_subcmd list ls'   -l difficulty      -d 'Filter by difficulty' -xa 'trivial easy medium hard very_hard'
    complete -c $cmd -n '__woco_tasks_subcmd list ls'   -l ready           -d 'Only ready tasks'
    complete -c $cmd -n '__woco_tasks_subcmd list ls'   -l include-archive -d 'Include archived'
    complete -c $cmd -n '__woco_tasks_subcmd list ls'   -l output          -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__woco_tasks_subcmd list ls'   -s o               -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__woco_tasks_subcmd list ls'   -l fields          -d 'Fields to show' -x

    complete -c $cmd -n '__woco_tasks_subcmd add a'     -l desc            -d 'Description' -x
    complete -c $cmd -n '__woco_tasks_subcmd add a'     -l description     -d 'Description' -x
    complete -c $cmd -n '__woco_tasks_subcmd add a'     -l priority        -d 'Priority' -xa 'critical high medium low wishlist'
    complete -c $cmd -n '__woco_tasks_subcmd add a'     -l difficulty      -d 'Difficulty' -xa 'trivial easy medium hard very_hard'
    complete -c $cmd -n '__woco_tasks_subcmd add a'     -l effort          -d 'Effort estimate' -x
    complete -c $cmd -n '__woco_tasks_subcmd add a'     -l depends-on      -d 'Dependencies' -x
    complete -c $cmd -n '__woco_tasks_subcmd add a'     -l dry-run         -d 'Dry run'
    complete -c $cmd -n '__woco_tasks_subcmd add a'     -l output          -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__woco_tasks_subcmd add a'     -s o               -d 'Output format' -xa 'text json toon'

    complete -c $cmd -n '__woco_tasks_subcmd set-status ss'     -l output  -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__woco_tasks_subcmd set-status ss'     -s o       -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__woco_tasks_subcmd set-status ss'     -l dry-run -d 'Dry run'

    complete -c $cmd -n '__woco_tasks_subcmd set-priority sp'   -l output  -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__woco_tasks_subcmd set-priority sp'   -s o       -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__woco_tasks_subcmd set-priority sp'   -l dry-run -d 'Dry run'

    complete -c $cmd -n '__woco_tasks_subcmd set-difficulty sd'  -l output  -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__woco_tasks_subcmd set-difficulty sd'  -s o       -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__woco_tasks_subcmd set-difficulty sd'  -l dry-run -d 'Dry run'

    complete -c $cmd -n '__woco_tasks_subcmd archive ar' -l dry-run -d 'Dry run'
    complete -c $cmd -n '__woco_tasks_subcmd archive ar' -l output  -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__woco_tasks_subcmd archive ar' -s o       -d 'Output format' -xa 'text json toon'

    complete -c $cmd -n '__woco_tasks_subcmd show sh'    -l output -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__woco_tasks_subcmd show sh'    -s o      -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__woco_tasks_subcmd show sh'    -l fields -d 'Fields to show' -x

    complete -c $cmd -n '__woco_tasks_subcmd graph g'    -l ascii    -d 'ASCII output'
    complete -c $cmd -n '__woco_tasks_subcmd graph g'    -l mermaid  -d 'Mermaid output'
    complete -c $cmd -n '__woco_tasks_subcmd graph g'    -l subtasks -d 'Include subtasks'
    complete -c $cmd -n '__woco_tasks_subcmd graph g'    -l status   -d 'Filter by status' -xa 'backlog planned in_progress blocked in_review done cancelled'
    complete -c $cmd -n '__woco_tasks_subcmd graph g'    -l output   -d 'Output format' -xa 'text json toon'
    complete -c $cmd -n '__woco_tasks_subcmd graph g'    -s o        -d 'Output format' -xa 'text json toon'
end
`;
}
