#!/usr/bin/env bun
/**
 * generate-fake-tasks.ts — Standalone test utility to generate complex task
 * trees as YAML files for testing the orchestration engine.
 *
 * Usage:
 *   bun tests/fixtures/generate-fake-tasks.ts [preset] [options]
 *
 * Presets:
 *   linear-chain   A→B→C→D (sequential dependency chain)
 *   fan-out        A→{B,C,D,E} (one task fans out to many)
 *   fan-in         {A,B,C,D}→E (many tasks converge to one)
 *   diamond        A→{B,C}→D (classic diamond dependency)
 *   deep-tree      Multi-level tree with branching and convergence (3-4 levels)
 *   stress         N tasks with randomized dependencies (default N=20)
 *   mixed          Combines all presets into one complex graph (~15-25 tasks)
 *
 * Options:
 *   --output, -o <path>   Output file path (default: stdout)
 *   --count, -n <number>  Number of tasks for stress preset (default: 20)
 *   --seed, -s <number>   Random seed for stress preset (default: 42)
 *   --sleep <ms>          Base sleep duration in ms (default: 1000)
 *   --help, -h            Show this help message
 *
 * Examples:
 *   bun tests/fixtures/generate-fake-tasks.ts diamond
 *   bun tests/fixtures/generate-fake-tasks.ts stress -n 50 -o stress-tasks.yml
 *   bun tests/fixtures/generate-fake-tasks.ts mixed --sleep 2000
 */

import { stringify as stringifyYaml } from "yaml";
import { writeFileSync } from "node:fs";

// ---------------------------------------------------------------------------
// Types (standalone — no imports from src/ to keep this self-contained)
// ---------------------------------------------------------------------------

type TaskStatus = "planned";
type Priority = "critical" | "high" | "medium" | "low" | "wishlist";
type Difficulty = "trivial" | "easy" | "medium" | "hard" | "very_hard";

interface FakeTask {
  id: string;
  title: string;
  description: string;
  status: TaskStatus;
  completion: number;
  difficulty: Difficulty;
  priority: Priority;
  depends_on: string[];
  effort: string;
  started_at: null;
  ended_at: null;
  constraints: string[];
  forbidden: string[];
  references: string[];
  notes: string[];
  subtasks: never[];
}

interface TasksFileOutput {
  version: string;
  meta: {
    created_at: string;
    updated_at: string;
    project: string;
    generator: string;
    maintainer: string;
  };
  tasks: FakeTask[];
}

type Preset =
  | "linear-chain"
  | "fan-out"
  | "fan-in"
  | "diamond"
  | "deep-tree"
  | "stress"
  | "mixed";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const PRIORITIES: Priority[] = ["critical", "high", "medium", "low", "wishlist"];
const DIFFICULTIES: Difficulty[] = ["trivial", "easy", "medium", "hard", "very_hard"];
const EFFORTS = [
  "PT1M",
  "PT5M",
  "PT10M",
  "PT15M",
  "PT20M",
  "PT30M",
  "PT1H",
  "PT2H",
  "PT4H",
  "PT8H",
  "PT12H",
  "P1D",
  "PT30M",
];

const ALL_PRESETS: Preset[] = [
  "linear-chain",
  "fan-out",
  "fan-in",
  "diamond",
  "deep-tree",
  "stress",
  "mixed",
];

// ---------------------------------------------------------------------------
// Seeded PRNG (simple mulberry32 — deterministic output for tests)
// ---------------------------------------------------------------------------

function mulberry32(seed: number): () => number {
  let s = seed | 0;
  return () => {
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeTask(
  id: string,
  title: string,
  opts: {
    dependsOn?: string[];
    sleepMs?: number;
    priority?: Priority;
    difficulty?: Difficulty;
    effort?: string;
  } = {}
): FakeTask {
  const sleepMs = opts.sleepMs ?? 1000;
  return {
    id,
    title,
    description: `FAKE_SLEEP_MS=${sleepMs}\nGenerated fake task for orchestration testing.`,
    status: "planned",
    completion: 0,
    difficulty: opts.difficulty ?? "medium",
    priority: opts.priority ?? "medium",
    depends_on: opts.dependsOn ?? [],
    effort: opts.effort ?? "PT10M",
    started_at: null,
    ended_at: null,
    constraints: [],
    forbidden: [],
    references: [],
    notes: [`Auto-generated by generate-fake-tasks.ts`],
    subtasks: [] as never[],
  };
}

function pickRandom<T>(arr: T[], rand: () => number): T {
  return arr[Math.floor(rand() * arr.length)];
}

function wrapOutput(tasks: FakeTask[]): TasksFileOutput {
  const now = new Date().toISOString();
  return {
    version: "1.0",
    meta: {
      created_at: now,
      updated_at: now,
      project: "fake-task-test",
      generator: "generate-fake-tasks.ts",
      maintainer: "test-harness",
    },
    tasks,
  };
}

// ---------------------------------------------------------------------------
// Preset Generators
// ---------------------------------------------------------------------------

/**
 * linear-chain: A→B→C→D (sequential dependency chain)
 */
function generateLinearChain(sleepMs: number): FakeTask[] {
  const labels = ["a", "b", "c", "d"];
  return labels.map((label, i) =>
    makeTask(`fake-chain-${label}`, `Chain Step ${label.toUpperCase()}`, {
      dependsOn: i > 0 ? [`fake-chain-${labels[i - 1]}`] : [],
      sleepMs: sleepMs + i * 500,
      priority: i === 0 ? "high" : i === labels.length - 1 ? "low" : "medium",
      difficulty: i === 0 ? "easy" : "medium",
      effort: EFFORTS[i % EFFORTS.length],
    })
  );
}

/**
 * fan-out: A→{B,C,D,E} (one task fans out to many independent tasks)
 */
function generateFanOut(sleepMs: number): FakeTask[] {
  const root = makeTask("fake-fanout-root", "Fan-Out Root", {
    sleepMs,
    priority: "high",
    difficulty: "easy",
    effort: "PT5M",
  });

  const branches = ["b", "c", "d", "e"].map((label, i) =>
    makeTask(`fake-fanout-${label}`, `Fan-Out Branch ${label.toUpperCase()}`, {
      dependsOn: ["fake-fanout-root"],
      sleepMs: sleepMs + (i + 1) * 300,
      priority: PRIORITIES[(i + 1) % PRIORITIES.length],
      difficulty: DIFFICULTIES[i % DIFFICULTIES.length],
      effort: EFFORTS[(i + 2) % EFFORTS.length],
    })
  );

  return [root, ...branches];
}

/**
 * fan-in: {A,B,C,D}→E (many independent tasks converge to one)
 */
function generateFanIn(sleepMs: number): FakeTask[] {
  const sources = ["a", "b", "c", "d"].map((label, i) =>
    makeTask(`fake-fanin-${label}`, `Fan-In Source ${label.toUpperCase()}`, {
      sleepMs: sleepMs + i * 200,
      priority: PRIORITIES[i % PRIORITIES.length],
      difficulty: DIFFICULTIES[(i + 1) % DIFFICULTIES.length],
      effort: EFFORTS[(i + 3) % EFFORTS.length],
    })
  );

  const sink = makeTask("fake-fanin-sink", "Fan-In Sink", {
    dependsOn: sources.map((s) => s.id),
    sleepMs: sleepMs + 1000,
    priority: "critical",
    difficulty: "hard",
    effort: "PT30M",
  });

  return [...sources, sink];
}

/**
 * diamond: A→{B,C}→D (classic diamond dependency)
 */
function generateDiamond(sleepMs: number): FakeTask[] {
  const top = makeTask("fake-diamond-top", "Diamond Top", {
    sleepMs,
    priority: "high",
    difficulty: "easy",
    effort: "PT5M",
  });

  const left = makeTask("fake-diamond-left", "Diamond Left", {
    dependsOn: ["fake-diamond-top"],
    sleepMs: sleepMs + 500,
    priority: "medium",
    difficulty: "medium",
    effort: "PT15M",
  });

  const right = makeTask("fake-diamond-right", "Diamond Right", {
    dependsOn: ["fake-diamond-top"],
    sleepMs: sleepMs + 700,
    priority: "medium",
    difficulty: "hard",
    effort: "PT20M",
  });

  const bottom = makeTask("fake-diamond-bottom", "Diamond Bottom", {
    dependsOn: ["fake-diamond-left", "fake-diamond-right"],
    sleepMs: sleepMs + 300,
    priority: "low",
    difficulty: "easy",
    effort: "PT10M",
  });

  return [top, left, right, bottom];
}

/**
 * deep-tree: Multi-level tree with branching and convergence (3-4 levels)
 *
 * Level 0:  root
 * Level 1:  l1-a, l1-b
 * Level 2:  l2-a (from l1-a), l2-b (from l1-a), l2-c (from l1-b), l2-d (from l1-b)
 * Level 3:  l3-merge (from l2-b, l2-c) — convergence point
 *           l3-leaf-a (from l2-a), l3-leaf-b (from l2-d)
 */
function generateDeepTree(sleepMs: number): FakeTask[] {
  const tasks: FakeTask[] = [];

  // Level 0
  tasks.push(
    makeTask("fake-deep-root", "Deep Tree Root", {
      sleepMs,
      priority: "critical",
      difficulty: "trivial",
      effort: "PT1M",
    })
  );

  // Level 1
  tasks.push(
    makeTask("fake-deep-l1-a", "Deep Tree L1-A", {
      dependsOn: ["fake-deep-root"],
      sleepMs: sleepMs + 200,
      priority: "high",
      difficulty: "easy",
      effort: "PT5M",
    })
  );
  tasks.push(
    makeTask("fake-deep-l1-b", "Deep Tree L1-B", {
      dependsOn: ["fake-deep-root"],
      sleepMs: sleepMs + 300,
      priority: "high",
      difficulty: "medium",
      effort: "PT10M",
    })
  );

  // Level 2
  tasks.push(
    makeTask("fake-deep-l2-a", "Deep Tree L2-A", {
      dependsOn: ["fake-deep-l1-a"],
      sleepMs: sleepMs + 400,
      priority: "medium",
      difficulty: "medium",
      effort: "PT15M",
    })
  );
  tasks.push(
    makeTask("fake-deep-l2-b", "Deep Tree L2-B", {
      dependsOn: ["fake-deep-l1-a"],
      sleepMs: sleepMs + 500,
      priority: "medium",
      difficulty: "hard",
      effort: "PT20M",
    })
  );
  tasks.push(
    makeTask("fake-deep-l2-c", "Deep Tree L2-C", {
      dependsOn: ["fake-deep-l1-b"],
      sleepMs: sleepMs + 350,
      priority: "low",
      difficulty: "easy",
      effort: "PT10M",
    })
  );
  tasks.push(
    makeTask("fake-deep-l2-d", "Deep Tree L2-D", {
      dependsOn: ["fake-deep-l1-b"],
      sleepMs: sleepMs + 600,
      priority: "low",
      difficulty: "medium",
      effort: "PT15M",
    })
  );

  // Level 3 — convergence and leaves
  tasks.push(
    makeTask("fake-deep-l3-merge", "Deep Tree L3 Merge", {
      dependsOn: ["fake-deep-l2-b", "fake-deep-l2-c"],
      sleepMs: sleepMs + 800,
      priority: "high",
      difficulty: "very_hard",
      effort: "PT30M",
    })
  );
  tasks.push(
    makeTask("fake-deep-l3-leaf-a", "Deep Tree L3 Leaf A", {
      dependsOn: ["fake-deep-l2-a"],
      sleepMs: sleepMs + 250,
      priority: "wishlist",
      difficulty: "trivial",
      effort: "PT5M",
    })
  );
  tasks.push(
    makeTask("fake-deep-l3-leaf-b", "Deep Tree L3 Leaf B", {
      dependsOn: ["fake-deep-l2-d"],
      sleepMs: sleepMs + 450,
      priority: "medium",
      difficulty: "easy",
      effort: "PT10M",
    })
  );

  return tasks;
}

/**
 * stress: Generates N tasks with randomized dependencies.
 * Ensures a valid DAG (no cycles) by only allowing deps on tasks with lower indices.
 */
function generateStress(
  sleepMs: number,
  count: number,
  seed: number
): FakeTask[] {
  const rand = mulberry32(seed);
  const tasks: FakeTask[] = [];

  for (let i = 0; i < count; i++) {
    const id = `fake-stress-${String(i + 1).padStart(3, "0")}`;
    const title = `Stress Task ${i + 1}`;

    // Determine dependencies: pick 0-3 random tasks from earlier in the list
    const deps: string[] = [];
    if (i > 0) {
      const maxDeps = Math.min(3, i);
      const numDeps = Math.floor(rand() * (maxDeps + 1));
      const candidates = tasks.map((t) => t.id);
      // Shuffle candidates and pick first numDeps
      for (let d = 0; d < numDeps; d++) {
        const idx = Math.floor(rand() * candidates.length);
        const picked = candidates.splice(idx, 1)[0];
        if (picked) deps.push(picked);
      }
    }

    tasks.push(
      makeTask(id, title, {
        dependsOn: deps,
        sleepMs: sleepMs + Math.floor(rand() * 3000),
        priority: pickRandom(PRIORITIES, rand),
        difficulty: pickRandom(DIFFICULTIES, rand),
        effort: pickRandom(EFFORTS, rand),
      })
    );
  }

  return tasks;
}

/**
 * mixed: Combines all presets into one complex graph (~15-25 tasks).
 * Adds cross-topology dependencies for realism.
 */
function generateMixed(sleepMs: number, seed: number): FakeTask[] {
  const rand = mulberry32(seed);
  const tasks: FakeTask[] = [];

  // 1. Start with a linear chain (4 tasks)
  const chain = generateLinearChain(sleepMs);
  tasks.push(...chain);

  // 2. Fan-out from the end of the chain (5 tasks)
  const fanOut = generateFanOut(sleepMs);
  // Re-prefix to avoid collisions
  const fanOutPrefixed = fanOut.map((t, i) => ({
    ...t,
    id: t.id.replace("fake-fanout-", "fake-mix-fo-"),
    depends_on: i === 0
      ? [chain[chain.length - 1].id] // root depends on chain end
      : [t.depends_on[0]?.replace("fake-fanout-", "fake-mix-fo-") ?? ""],
  }));
  tasks.push(...fanOutPrefixed);

  // 3. Diamond joining two fan-out branches (4 tasks)
  const diamond = generateDiamond(sleepMs);
  const diamondPrefixed = diamond.map((t) => ({
    ...t,
    id: t.id.replace("fake-diamond-", "fake-mix-dm-"),
    depends_on: t.depends_on.map((d) =>
      d.replace("fake-diamond-", "fake-mix-dm-")
    ),
  }));
  // Diamond top depends on two fan-out branches
  diamondPrefixed[0].depends_on = [fanOutPrefixed[1].id, fanOutPrefixed[2].id];
  tasks.push(...diamondPrefixed);

  // 4. Fan-in: gather diamond bottom + remaining fan-out branches (5 tasks)
  const fanIn = generateFanIn(sleepMs);
  const fanInPrefixed = fanIn.map((t) => ({
    ...t,
    id: t.id.replace("fake-fanin-", "fake-mix-fi-"),
    depends_on: t.depends_on.map((d) =>
      d.replace("fake-fanin-", "fake-mix-fi-")
    ),
  }));
  // Fan-in sources: some depend on diamond bottom, some are independent
  fanInPrefixed[0].depends_on = [diamondPrefixed[3].id]; // from diamond bottom
  fanInPrefixed[1].depends_on = [fanOutPrefixed[3].id]; // from a fan-out branch
  // The sink's depends_on already points to the other fan-in sources
  fanInPrefixed[4].depends_on = fanInPrefixed.slice(0, 4).map((t) => t.id);
  tasks.push(...fanInPrefixed);

  // 5. Add a couple of random cross-links for extra complexity
  // Final capstone task depends on fan-in sink + deep-tree-like convergence
  tasks.push(
    makeTask("fake-mix-capstone", "Mixed Capstone", {
      dependsOn: [fanInPrefixed[4].id, diamondPrefixed[3].id],
      sleepMs: sleepMs + 2000,
      priority: "critical",
      difficulty: "very_hard",
      effort: "PT30M",
    })
  );

  // Vary priorities and difficulties more
  for (const t of tasks) {
    if (rand() < 0.3) {
      t.priority = pickRandom(PRIORITIES, rand);
    }
    if (rand() < 0.3) {
      t.difficulty = pickRandom(DIFFICULTIES, rand);
    }
  }

  return tasks;
}

// ---------------------------------------------------------------------------
// Main Generator Function (exported for programmatic use)
// ---------------------------------------------------------------------------

export interface GeneratorOptions {
  preset: Preset;
  sleepMs?: number;
  count?: number;
  seed?: number;
}

/**
 * Generate a fake task tree for the given preset.
 * Returns a full TasksFile-compatible YAML structure.
 */
export function generateFakeTasks(opts: GeneratorOptions): TasksFileOutput {
  const sleepMs = opts.sleepMs ?? 1000;
  const count = opts.count ?? 20;
  const seed = opts.seed ?? 42;

  let tasks: FakeTask[];

  switch (opts.preset) {
    case "linear-chain":
      tasks = generateLinearChain(sleepMs);
      break;
    case "fan-out":
      tasks = generateFanOut(sleepMs);
      break;
    case "fan-in":
      tasks = generateFanIn(sleepMs);
      break;
    case "diamond":
      tasks = generateDiamond(sleepMs);
      break;
    case "deep-tree":
      tasks = generateDeepTree(sleepMs);
      break;
    case "stress":
      tasks = generateStress(sleepMs, count, seed);
      break;
    case "mixed":
      tasks = generateMixed(sleepMs, seed);
      break;
    default:
      throw new Error(
        `Unknown preset: ${opts.preset}. Valid presets: ${ALL_PRESETS.join(", ")}`
      );
  }

  return wrapOutput(tasks);
}

/**
 * Generate YAML string for a given preset.
 */
export function generateFakeTasksYaml(opts: GeneratorOptions): string {
  const data = generateFakeTasks(opts);
  return stringifyYaml(data, {
    lineWidth: 120,
    defaultKeyType: "PLAIN",
    defaultStringType: "QUOTE_DOUBLE",
  });
}

// ---------------------------------------------------------------------------
// CLI Entry Point
// ---------------------------------------------------------------------------

function printHelp(): void {
  console.log(`
generate-fake-tasks.ts — Generate complex task trees as YAML for testing

Usage:
  bun tests/fixtures/generate-fake-tasks.ts [preset] [options]

Presets:
  linear-chain   A→B→C→D (sequential dependency chain)
  fan-out        A→{B,C,D,E} (one task fans out to many)
  fan-in         {A,B,C,D}→E (many tasks converge to one)
  diamond        A→{B,C}→D (classic diamond dependency)
  deep-tree      Multi-level tree with branching and convergence
  stress         N tasks with randomized dependencies (default N=20)
  mixed          Combines all presets into one complex graph

Options:
  --output, -o <path>   Output file path (default: stdout)
  --count, -n <number>  Number of tasks for stress preset (default: 20)
  --seed, -s <number>   Random seed for stress preset (default: 42)
  --sleep <ms>          Base sleep duration in ms (default: 1000)
  --help, -h            Show this help message
  --all                 Generate all presets (one file each, requires -o dir)

Examples:
  bun tests/fixtures/generate-fake-tasks.ts diamond
  bun tests/fixtures/generate-fake-tasks.ts stress -n 50 -o stress-tasks.yml
  bun tests/fixtures/generate-fake-tasks.ts mixed --sleep 2000
  bun tests/fixtures/generate-fake-tasks.ts --all -o tests/fixtures/output/
`);
}

function parseArgs(
  argv: string[]
): {
  preset: Preset | null;
  output: string | null;
  count: number;
  seed: number;
  sleepMs: number;
  help: boolean;
  all: boolean;
} {
  const result = {
    preset: null as Preset | null,
    output: null as string | null,
    count: 20,
    seed: 42,
    sleepMs: 1000,
    help: false,
    all: false,
  };

  let i = 0;
  while (i < argv.length) {
    const arg = argv[i];

    if (arg === "--help" || arg === "-h") {
      result.help = true;
      i++;
    } else if (arg === "--all") {
      result.all = true;
      i++;
    } else if (arg === "--output" || arg === "-o") {
      result.output = argv[++i] ?? null;
      i++;
    } else if (arg === "--count" || arg === "-n") {
      result.count = parseInt(argv[++i] ?? "20", 10);
      i++;
    } else if (arg === "--seed" || arg === "-s") {
      result.seed = parseInt(argv[++i] ?? "42", 10);
      i++;
    } else if (arg === "--sleep") {
      result.sleepMs = parseInt(argv[++i] ?? "1000", 10);
      i++;
    } else if (!arg.startsWith("-") && !result.preset) {
      if (!ALL_PRESETS.includes(arg as Preset)) {
        console.error(`Unknown preset: ${arg}`);
        console.error(`Valid presets: ${ALL_PRESETS.join(", ")}`);
        process.exit(1);
      }
      result.preset = arg as Preset;
      i++;
    } else {
      console.error(`Unknown argument: ${arg}`);
      process.exit(1);
    }
  }

  return result;
}

// Only run CLI when executed directly (not imported)
if (import.meta.main) {
  // Skip the first two args (bun, script path)
  const args = process.argv.slice(2);
  const parsed = parseArgs(args);

  if (parsed.help) {
    printHelp();
    process.exit(0);
  }

  if (parsed.all) {
    // Generate all presets
    for (const preset of ALL_PRESETS) {
      const yaml = generateFakeTasksYaml({
        preset,
        sleepMs: parsed.sleepMs,
        count: parsed.count,
        seed: parsed.seed,
      });

      if (parsed.output) {
        const outPath = `${parsed.output.replace(/\/$/, "")}/${preset}.yml`;
        writeFileSync(outPath, yaml);
        console.log(`  ✓ ${preset} → ${outPath}`);
      } else {
        console.log(`\n--- ${preset} ---`);
        console.log(yaml);
      }
    }
    process.exit(0);
  }

  if (!parsed.preset) {
    console.error("Error: No preset specified.");
    console.error(`Valid presets: ${ALL_PRESETS.join(", ")}`);
    console.error('Run with --help for usage information.');
    process.exit(1);
  }

  const yaml = generateFakeTasksYaml({
    preset: parsed.preset,
    sleepMs: parsed.sleepMs,
    count: parsed.count,
    seed: parsed.seed,
  });

  if (parsed.output) {
    writeFileSync(parsed.output, yaml);
    console.log(`Written to ${parsed.output}`);
  } else {
    process.stdout.write(yaml);
  }
}
